name: FromDoppler

on:
  pull_request:
    branches: [$default-branch]
  push:
    branches: [$default-branch, "INT"]
    tags:
      - v*.*.*

jobs:
  fromdoppler:
    name: Conventions
    uses: FromDoppler/.github/.github/workflows/conventions.yml@main
  dotnet:
    name: Continuous Integration
    uses: FromDoppler/.github/.github/workflows/dotnet.yml@main
  nuget:
    if: ${{ github.event_name == 'push' }}
    name: Continuous Delivery
    uses: FromDoppler/.github/.github/workflows/continuous-delivery-nuget.yml@main
  docker:
    if: ${{ github.event_name == 'push' }}
    name: Continuous Delivery Default Project
    uses: FromDoppler/.github/.github/workflows/continuous-delivery-dockerfile.yml@main
    secrets: inherit
    with:
      dockerfile-path: "DefaultProject/Dockerfile"
      docker-image-name: "doppler-docker-image-name-default-example"
  docker-another:
    if: ${{ github.event_name == 'push' }}
    name: Continuous Delivery Another Project
    uses: FromDoppler/.github/.github/workflows/continuous-delivery-dockerfile.yml@main
    secrets: inherit
    with:
      dockerfile-path: "AnotherProject/Dockerfile"
      docker-image-name: "doppler-docker-image-name-another-example"
