name: Continuous Delivery

on:
  workflow_call:
    inputs:
      docker-compose-path:
        description: "Path to docker-compose.yml to use for build images"
        default: "docker-compose.yml"
        type: string

env:
  SOURCE_VERSION: "${{ github.ref_name }}+${{ github.sha }}@${{ github.server_url}}/${{ github.repository }}"
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  semver:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.v.outputs.version}}
      is-semver: ${{ steps.v.outputs.is-semver }}
      major: v${{ steps.v.outputs.major }}
      minor: v${{ steps.v.outputs.major }}.${{ steps.v.outputs.minor }}
      patch: v${{ steps.v.outputs.major }}.${{ steps.v.outputs.minor }}.${{ steps.v.outputs.patch }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Identify Version
        id: v
        uses: battila7/get-version-action@v2

  github-packages:
    name: Docker image to Github Packages
    runs-on: ubuntu-latest
    needs: semver
    permissions:
      contents: read
      packages: write
    env:
      REGISTRY: ghcr.io
      IMAGE_NAME: ${{ github.repository }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker images version
        env:
          VERSION: ${{ needs.semver.outputs.version }}
        run: |
          docker-compose build --file ${{ inputs.docker-compose-path }}
          docker-compose push --file ${{ inputs.docker-compose-path }}

      - name: Docker images latest
        if: ${{ needs.semver.outputs.is-semver }}
        run: |
          docker-compose build --file ${{ inputs.docker-compose-path }}
          docker-compose push --file ${{ inputs.docker-compose-path }}

      - name: Docker images version major
        if: ${{ needs.semver.outputs.is-semver }}
        env:
          VERSION: ${{ needs.semver.outputs.major }}
        run: |
          docker-compose build --file ${{ inputs.docker-compose-path }}
          docker-compose push --file ${{ inputs.docker-compose-path }}

      - name: Docker images version major.minor
        if: ${{ needs.semver.outputs.is-semver }}
        env:
          VERSION: ${{ needs.semver.outputs.minor }}
        run: |
          docker-compose build --file ${{ inputs.docker-compose-path }}
          docker-compose push --file ${{ inputs.docker-compose-path }}

      - name: Docker images version major.minor.patch
        if: ${{ needs.semver.outputs.is-semver }}
        env:
          VERSION: ${{ needs.semver.outputs.patch }}
        run: |
          docker-compose build --file ${{ inputs.docker-compose-path }}
          docker-compose push --file ${{ inputs.docker-compose-path }}

  docker-hub:
    name: Docker images to Docker Hub
    runs-on: ubuntu-latest
    needs: semver
    steps:
      - uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Docker images version
        env:
          VERSION: ${{ needs.semver.outputs.version }}
        run: |
          docker-compose build --file ${{ inputs.docker-compose-path }}
          docker-compose push --file ${{ inputs.docker-compose-path }}

      - name: Docker images latest
        if: ${{ needs.semver.outputs.is-semver }}
        run: |
          docker-compose build --file ${{ inputs.docker-compose-path }}
          docker-compose push --file ${{ inputs.docker-compose-path }}

      - name: Docker images version major
        if: ${{ needs.semver.outputs.is-semver }}
        env:
          VERSION: ${{ needs.semver.outputs.major }}
        run: |
          docker-compose build --file ${{ inputs.docker-compose-path }}
          docker-compose push --file ${{ inputs.docker-compose-path }}

      - name: Docker images version major.minor
        if: ${{ needs.semver.outputs.is-semver }}
        env:
          VERSION: ${{ needs.semver.outputs.minor }}
        run: |
          docker-compose build --file ${{ inputs.docker-compose-path }}
          docker-compose push --file ${{ inputs.docker-compose-path }}

      - name: Docker images version major.minor.patch
        if: ${{ needs.semver.outputs.is-semver }}
        env:
          VERSION: ${{ needs.semver.outputs.patch }}
        run: |
          docker-compose build --file ${{ inputs.docker-compose-path }}
          docker-compose push --file ${{ inputs.docker-compose-path }}
